apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/GonzaV/gitops-argo.git
    targetRevision: demo
    path: manifests/nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-demo
  syncPolicy:
    automated: {
      selfHeal: true
    }
    syncOptions:
      - CreateNamespace=true
